

/*
 * - Generated by Gate
 * 
 * - Embarks planes
 * - Disembarks planes at gate
 */

public class Passenger implements Runnable {

    @Override
    public void run() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'run'");
    }

}
